# Generated by Django 5.0.9 on 2024-11-06 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SYgtway1',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('cmpid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cmpname', models.CharField(max_length=100)),
                ('schname', models.CharField(max_length=50)),
                ('dbusr', models.CharField(max_length=50)),
                ('dbpwd', models.CharField(max_length=50)),
                ('dbname', models.CharField(max_length=50)),
                ('cmpstatus', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'SYgtway1',
            },
        ),
        migrations.CreateModel(
            name='SYgtway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('logid', models.CharField(max_length=50)),
                ('logcmpid', models.CharField(max_length=50, null=True, unique=True)),
                ('logpwd', models.CharField(max_length=128)),
                ('login', models.DateTimeField(blank=True, null=True)),
                ('logout', models.DateTimeField(blank=True, null=True)),
                ('lcked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('cmpid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sygtway1')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'SYgtway',
            },
        ),
    ]
